# Generated by Django 5.1.4 on 2025-03-09 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpeechApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestuseractivity',
            name='translated_text',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='translated_text',
        ),
    ]
